version: '3.8'
services:
  app:
    container_name: colmenalab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/nestjs_db
    depends_on:
      - db

  db:
    container_name: postgresdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
